preload = /home/vcnvim/Pictures/Wallpapers/dark_abstract.jpg
preload = /home/vcnvim/Pictures/Wallpapers/anime_art.jpg
preload = /home/vcnvim/Pictures/Wallpapers/scenic_mountain.jpg

wallpaper = eDP-1,/home/vcnvim/Pictures/Wallpapers/dark_abstract.jpg
ipc = on
